import type { TorrentSummary } from "@/lib/types";

const GB = 1024 ** 3;
const MB = 1024 ** 2;

/** Sample data used for UI previews in a plain browser or with VITE_DEMO=1. */
export const demoTorrents: TorrentSummary[] = [
  {
    id: 1,
    name: "debian-13.1.0-amd64-DVD-1.iso",
    totalBytes: 3.9 * GB,
    progress: 0.64,
    state: "downloading",
    downloadSpeed: 11.2 * MB,
    uploadSpeed: 2.5 * MB,
    downloadedBytes: 2.5 * GB,
    uploadedBytes: 410 * MB,
    eta: 135,
    elapsed: 511,
    seeds: 21,
    peers: 8,
  },
  {
    id: 2,
    name: "Blender Open Movie Soundtracks.flac",
    totalBytes: 820 * MB,
    progress: 0.37,
    state: "downloading",
    downloadSpeed: 4.1 * MB,
    uploadSpeed: 310 * 1024,
    downloadedBytes: 303 * MB,
    uploadedBytes: 41 * MB,
    eta: 900,
    elapsed: 300,
    seeds: 54,
    peers: 18,
  },
  {
    id: 3,
    name: "Sintel (2010) 1080p.mkv",
    totalBytes: 2.2 * GB,
    progress: 1,
    state: "seeding",
    downloadSpeed: 0,
    uploadSpeed: 7.6 * MB,
    downloadedBytes: 2.2 * GB,
    uploadedBytes: 3.1 * GB,
    eta: null,
    elapsed: 86_400,
    seeds: 9,
    peers: 2,
  },
  {
    id: 4,
    name: "Big Buck Bunny 4K 60fps.mp4",
    totalBytes: 1.4 * GB,
    progress: 0.81,
    state: "paused",
    downloadSpeed: 0,
    uploadSpeed: 0,
    downloadedBytes: 1.13 * GB,
    uploadedBytes: 96 * MB,
    eta: null,
    elapsed: 4_200,
    seeds: 11,
    peers: 21,
  },
  {
    id: 5,
    name: "Project Gutenberg Top 100.epub",
    totalBytes: 312 * MB,
    progress: 0.42,
    state: "paused",
    downloadSpeed: 0,
    uploadSpeed: 0,
    downloadedBytes: 131 * MB,
    uploadedBytes: 0,
    eta: null,
    elapsed: 960,
    seeds: 11,
    peers: 21,
  },
  {
    id: 6,
    name: "archlinux-2026.10.01-x86_64.iso",
    totalBytes: 1.2 * GB,
    progress: 1,
    state: "paused",
    downloadSpeed: 0,
    uploadSpeed: 0,
    downloadedBytes: 1.2 * GB,
    uploadedBytes: 2.4 * GB,
    eta: null,
    elapsed: 172_800,
    seeds: 0,
    peers: 0,
  },
];
